version: 2
updates:
  - package-ecosystem: docker
    directory: /ubuntu
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
